// auth
export const LOGOUT_USER = 'LOGOUT_USER';
export const STORE_USER_INFO = 'STORE_USER_INFO';

// restaurants
export const ADD_NEW_RESTAURANT = 'ADD_NEW_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';
export const STORE_ACTIVE_RESTAURANT = 'STORE_ACTIVE_RESTAURANT';
export const STORE_USER_RESTAURANTS = 'STORE_USER_RESTAURANTS';

// mealperiods
export const ADD_MEAL_PERIOD = 'ADD_MEAL_PERIOD';
export const DELETE_MEAL_PERIOD = 'DELETE_MEAL_PERIOD';
export const UPDATE_MEAL_PERIOD = 'UPDATE_MEAL_PERIOD';

// categoryGroups
export const ADD_CATEGORY_GROUP = 'ADD_CATEGORY_GROUP';
export const DELETE_CATEGORY_GROUP = 'DELETE_CATEGORY_GROUP';
export const UPDATE_CATEGORY_GROUP = 'UPDATE_CATEGORY_GROUP';
