// auth
export const LOGOUT_USER = 'LOGOUT_USER';
export const STORE_USER_INFO = 'STORE_USER_INFO';

// users
// export const REGISTER_NEW_USER = 'REGISTER_NEW_USER';

// restaurants
export const ADD_NEW_RESTAURANT = 'ADD_NEW_RESTAURANT';
export const ADD_USER_TO_RESTAURANT = 'ADD_USER_TO_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const REMOVE_ACTIVE = 'REMOVE_ACTIVE';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';
export const STORE_ACTIVE_RESTAURANT = 'STORE_ACTIVE_RESTAURANT';
export const STORE_USER_RESTAURANTS = 'STORE_USER_RESTAURANTS';

// mealperiods
export const ADD_MEAL_PERIOD = 'ADD_MEAL_PERIOD';
export const DELETE_MEAL_PERIOD = 'DELETE_MEAL_PERIOD';
export const UPDATE_MEAL_PERIOD = 'UPDATE_MEAL_PERIOD';

// categoryGroups
export const ADD_CATEGORY_GROUP = 'ADD_CATEGORY_GROUP';
export const DELETE_CATEGORY_GROUP = 'DELETE_CATEGORY_GROUP';
export const UPDATE_CATEGORY_GROUP = 'UPDATE_CATEGORY_GROUP';

// categories
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';

// defaultsales
export const ADD_DEFAULT_SALE = 'ADD_DEFAULT_SALE';
export const DELETE_DEFAULT_SALE = 'DELETE_DEFAULT_SALE';
export const UPDATE_DEFAULT_SALE = 'UPDATE_DEFAULT_SALE';

// invoices
export const ADD_INVOICE = 'ADD_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';

// expenses
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';

// mealPeriodCats
export const ADD_MEAL_PERIOD_CATEGORY = 'ADD_MEAL_PERIOD_CATEGORY';
export const DELETE_MEAL_PERIOD_CATEGORY = 'DELETE_MEAL_PERIOD_CATEGORY';
export const UPDATE_MEAL_PERIOD_CATEGORY = 'UPDATE_MEAL_PERIOD_CATEGORY';

// sales
export const ADD_SALE = 'ADD_SALE';
export const DELETE_SALE = 'DELETE_SALE';
export const STORE_SALES = 'STORE_SALES';
// export const STORE_BLENDED_SALES = 'STORE_BLENDED_SALES';
export const UPDATE_SALE = 'UPDATE_SALE';

// budget
// export const CLEAR_ALL_BUDGET = 'CLEAR_ALL_BUDGET';
// export const STORE_BUDGET_SALES = 'STORE_BUDGET_SALES';
// export const STORE_BUDGET_BLENDED_SALES = 'STORE_BUDGET_BLENDED_SALES';
// export const STORE_WEEK_INVOICES = 'STORE_WEEK_INVOICES';
// export const STORE_WEEK_EXPENSES = 'STORE_WEEK_EXPENSES';
